{
 "title": "IoT Music Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Excepted Note",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select expected_note from mqtt_consumer;"
    }
   ]
  },
  {
   "title": "Actual Note",
   "type": "canvas",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "select actual_note from mqtt_consumer;"
    }
   ]
  },
  {
   "title": "Frequency Comparison",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select expected_frequency, actual_frequency, timestamp from mqtt_consumer;"
    }
   ]
  },
  {
   "title": "Duration Comparison",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select expected_length_seconds, actual_length_seconds, timestamp from mqtt_consumer;"
    }
   ]
  }
 ]
}