FROM python:3.12

WORKDIR /app

COPY ./ClientPart/requirements.txt ./
COPY ./ClientPart/main.py ./

RUN apt update
RUN apt install portaudio19-dev -y
RUN pip install -r requirements.txt

CMD [ "python", "./main.py" ]